const xlsx = require('xlsx');
const path = require('path');

const faculty = [
    {
        Name: "Dr. Arif Alvi",
        Phone: "03001112222",
        PrimaryEmail: "arif.alvi@example.com",
        SecondaryEmail: "alvi.a@gmail.com",
        Password: "password123",
        DepartmentName: "Computer Science",
        ProgramName: "BSCS",
        Term: "Fall-2023",
        CNIC: "61101-1111111-1",
        Address: "Sector F-7, Islamabad",
        Role: "faculty",
        facultyId: "FAC-001",
        designation: "Professor",
        extension: "101",
        DoB: "1970-01-01",
        joiningDate: "2010-01-01"
    },
    {
        Name: "Dr. Samina Yasmeen",
        Phone: "03211113333",
        PrimaryEmail: "samina.y@example.com",
        SecondaryEmail: "samina.yasmeen@gmail.com",
        Password: "password123",
        DepartmentName: "Software Engineering",
        ProgramName: "BSSE",
        Term: "Fall-2023",
        CNIC: "61101-2222222-2",
        Address: "DHA Phase 2, Lahore",
        Role: "hod",
        facultyId: "FAC-002",
        designation: "Associate Professor",
        extension: "102",
        DoB: "1975-05-15",
        joiningDate: "2012-03-20"
    },
    {
        Name: "Prof. Kamran Khan",
        Phone: "03334445555",
        PrimaryEmail: "kamran.khan@example.com",
        SecondaryEmail: "kamran.k@gmail.com",
        Password: "password123",
        DepartmentName: "Computer Science",
        ProgramName: "BSCS",
        Term: "Fall-2023",
        CNIC: "61101-3333333-3",
        Address: "Gulshan-e-Iqbal, Karachi",
        Role: "faculty",
        facultyId: "FAC-003",
        designation: "Professor",
        extension: "103",
        DoB: "1965-10-10",
        joiningDate: "2005-09-01"
    },
    {
        Name: "Dr. Uzma Qadri",
        Phone: "03456667777",
        PrimaryEmail: "uzma.qadri@example.com",
        SecondaryEmail: "uzma.q@gmail.com",
        Password: "password123",
        DepartmentName: "Software Engineering",
        ProgramName: "BSSE",
        Term: "Fall-2023",
        CNIC: "61101-4444444-4",
        Address: "Bahria Town, Rawalpindi",
        Role: "Coordinator",
        facultyId: "FAC-004",
        designation: "Assistant Professor",
        extension: "104",
        DoB: "1982-12-12",
        joiningDate: "2015-02-14"
    },
    {
        Name: "Mr. Shahid Afridi",
        Phone: "03007778888",
        PrimaryEmail: "shahid.afridi@example.com",
        SecondaryEmail: "afridi.s@gmail.com",
        Password: "password123",
        DepartmentName: "Computer Science",
        ProgramName: "BSCS",
        Term: "Fall-2023",
        CNIC: "61101-5555555-5",
        Address: "Peshawar Cantt, Peshawar",
        Role: "faculty",
        facultyId: "FAC-005",
        designation: "Lecturer",
        extension: "105",
        DoB: "1980-03-01",
        joiningDate: "2018-08-15"
    },
    {
        Name: "Ms. Sana Mir",
        Phone: "03128889999",
        PrimaryEmail: "sana.mir@example.com",
        SecondaryEmail: "sana.m@gmail.com",
        Password: "password123",
        DepartmentName: "Software Engineering",
        ProgramName: "BSSE",
        Term: "Fall-2023",
        CNIC: "61101-6666666-6",
        Address: "G-11, Islamabad",
        Role: "faculty",
        facultyId: "FAC-006",
        designation: "Lecturer",
        extension: "106",
        DoB: "1985-06-25",
        joiningDate: "2019-01-10"
    },
    {
        Name: "Dr. Abdul Qadeer",
        Phone: "03229990000",
        PrimaryEmail: "abdul.qadeer@example.com",
        SecondaryEmail: "qadeer.a@gmail.com",
        Password: "password123",
        DepartmentName: "Computer Science",
        ProgramName: "BSCS",
        Term: "Fall-2023",
        CNIC: "61101-7777777-7",
        Address: "KRL Colony, Islamabad",
        Role: "faculty",
        facultyId: "FAC-007",
        designation: "Professor",
        extension: "107",
        DoB: "1940-04-01",
        joiningDate: "1980-01-01"
    },
    {
        Name: "Prof. Atta-ur-Rahman",
        Phone: "03330001111",
        PrimaryEmail: "atta.rahman@example.com",
        SecondaryEmail: "atta.r@gmail.com",
        Password: "password123",
        DepartmentName: "Software Engineering",
        ProgramName: "BSSE",
        Term: "Fall-2023",
        CNIC: "61101-8888888-8",
        Address: "HEC Colony, Islamabad",
        Role: "faculty",
        facultyId: "FAC-008",
        designation: "Professor",
        extension: "108",
        DoB: "1942-09-22",
        joiningDate: "1985-05-05"
    },
    {
        Name: "Dr. Pervez Hoodbhoy",
        Phone: "03452223333",
        PrimaryEmail: "pervez.h@example.com",
        SecondaryEmail: "pervez.hoodbhoy@gmail.com",
        Password: "password123",
        DepartmentName: "Computer Science",
        ProgramName: "BSCS",
        Term: "Fall-2023",
        CNIC: "61101-9999999-9",
        Address: "Sector E-7, Islamabad",
        Role: "faculty",
        facultyId: "FAC-009",
        designation: "Professor",
        extension: "109",
        DoB: "1950-07-11",
        joiningDate: "1990-10-10"
    },
    {
        Name: "Ms. Maleeha Lodhi",
        Phone: "03003334444",
        PrimaryEmail: "maleeha.lodhi@example.com",
        SecondaryEmail: "maleeha.l@gmail.com",
        Password: "password123",
        DepartmentName: "Software Engineering",
        ProgramName: "BSSE",
        Term: "Fall-2023",
        CNIC: "61101-0000000-0",
        Address: "Diplomatic Enclave, Islamabad",
        Role: "faculty",
        facultyId: "FAC-010",
        designation: "Lecturer",
        extension: "110",
        DoB: "1952-12-15",
        joiningDate: "1995-12-15"
    }
];

const ws = xlsx.utils.json_to_sheet(faculty);
const wb = xlsx.utils.book_new();
xlsx.utils.book_append_sheet(wb, ws, "Faculty");

const filePath = path.join(__dirname, 'sample_faculty.xlsx');
xlsx.writeFile(wb, filePath);

console.log(`Excel file created at: ${filePath}`);
