const xlsx = require('xlsx');
const path = require('path');

const students = [
    {
        Name: "Ahmed Ali",
        Phone: "03001234567",
        PrimaryEmail: "ahmed.ali@example.com",
        SecondaryEmail: "ahmed.alt@gmail.com",
        Password: "password123",
        DepartmentName: "Computer Science",
        ProgramName: "BSCS",
        Term: "Fall-2023",
        CNIC: "61101-1234567-1",
        Address: "Street 1, Islamabad",
        Role: "Student",
        RegNum: "FA23-BSCS-001",
        CrHours: 15,
        CGPA: 3.5,
        GPA: 3.6
    },
    {
        Name: "Fatima Sheikh",
        Phone: "03217654321",
        PrimaryEmail: "fatima.sheikh@example.com",
        SecondaryEmail: "fatima.s@gmail.com",
        Password: "password123",
        DepartmentName: "Software Engineering",
        ProgramName: "BSSE",
        Term: "Fall-2023",
        CNIC: "61101-7654321-2",
        Address: "Block B, Lahore",
        Role: "Student",
        RegNum: "FA23-BSSE-002",
        CrHours: 18,
        CGPA: 3.8,
        GPA: 3.7
    },
    {
        Name: "Muhammad Usman",
        Phone: "03339876543",
        PrimaryEmail: "m.usman@example.com",
        SecondaryEmail: "usman.m@gmail.com",
        Password: "password123",
        DepartmentName: "Computer Science",
        ProgramName: "BSCS",
        Term: "Fall-2023",
        CNIC: "61101-9876543-3",
        Address: "Sector G-10, Islamabad",
        Role: "Student",
        RegNum: "FA23-BSCS-003",
        CrHours: 12,
        CGPA: 3.2,
        GPA: 3.1
    },
    {
        Name: "Aisha Khan",
        Phone: "03451112233",
        PrimaryEmail: "aisha.khan@example.com",
        SecondaryEmail: "aisha.k@gmail.com",
        Password: "password123",
        DepartmentName: "Software Engineering",
        ProgramName: "BSSE",
        Term: "Fall-2023",
        CNIC: "61101-1112233-4",
        Address: "DHA Phase 5, Karachi",
        Role: "Student",
        RegNum: "FA23-BSSE-004",
        CrHours: 16,
        CGPA: 3.9,
        GPA: 4.0
    },
    {
        Name: "Zeeshan Ahmed",
        Phone: "03012223344",
        PrimaryEmail: "zeeshan.a@example.com",
        SecondaryEmail: "zeeshan.ahmed@gmail.com",
        Password: "password123",
        DepartmentName: "Computer Science",
        ProgramName: "BSCS",
        Term: "Fall-2023",
        CNIC: "61101-2223344-5",
        Address: "Satellite Town, Rawalpindi",
        Role: "Student",
        RegNum: "FA23-BSCS-005",
        CrHours: 14,
        CGPA: 2.8,
        GPA: 3.0
    },
    {
        Name: "Sana Malik",
        Phone: "03125556677",
        PrimaryEmail: "sana.malik@example.com",
        SecondaryEmail: "sana.m@gmail.com",
        Password: "password123",
        DepartmentName: "Software Engineering",
        ProgramName: "BSSE",
        Term: "Fall-2023",
        CNIC: "61101-5556677-6",
        Address: "Gulberg III, Lahore",
        Role: "Student",
        RegNum: "FA23-BSSE-006",
        CrHours: 17,
        CGPA: 3.6,
        GPA: 3.5
    },
    {
        Name: "Bilal Hassan",
        Phone: "03224448899",
        PrimaryEmail: "bilal.h@example.com",
        SecondaryEmail: "bilal.hassan@gmail.com",
        Password: "password123",
        DepartmentName: "Computer Science",
        ProgramName: "BSCS",
        Term: "Fall-2023",
        CNIC: "61101-4448899-7",
        Address: "F-6, Islamabad",
        Role: "Student",
        RegNum: "FA23-BSCS-007",
        CrHours: 15,
        CGPA: 3.4,
        GPA: 3.3
    },
    {
        Name: "Maryam Noor",
        Phone: "03340001122",
        PrimaryEmail: "maryam.noor@example.com",
        SecondaryEmail: "m.noor@gmail.com",
        Password: "password123",
        DepartmentName: "Software Engineering",
        ProgramName: "BSSE",
        Term: "Fall-2023",
        CNIC: "61101-0001122-8",
        Address: "North Nazimabad, Karachi",
        Role: "Student",
        RegNum: "FA23-BSSE-008",
        CrHours: 16,
        CGPA: 3.7,
        GPA: 3.8
    },
    {
        Name: "Hamza Rashid",
        Phone: "03009990000",
        PrimaryEmail: "hamza.r@example.com",
        SecondaryEmail: "hamza.rashid@gmail.com",
        Password: "password123",
        DepartmentName: "Computer Science",
        ProgramName: "BSCS",
        Term: "Fall-2023",
        CNIC: "61101-9990000-9",
        Address: "Wapda Town, Multan",
        Role: "Student",
        RegNum: "FA23-BSCS-009",
        CrHours: 13,
        CGPA: 3.1,
        GPA: 3.2
    },
    {
        Name: "Zainab Batool",
        Phone: "03211234432",
        PrimaryEmail: "zainab.b@example.com",
        SecondaryEmail: "zainab.batool@gmail.com",
        Password: "password123",
        DepartmentName: "Software Engineering",
        ProgramName: "BSSE",
        Term: "Fall-2023",
        CNIC: "61101-1234432-0",
        Address: "Model Town, Gujranwala",
        Role: "Student",
        RegNum: "FA23-BSSE-010",
        CrHours: 18,
        CGPA: 3.9,
        GPA: 3.9
    }
];

const ws = xlsx.utils.json_to_sheet(students);
const wb = xlsx.utils.book_new();
xlsx.utils.book_append_sheet(wb, ws, "Students");

const filePath = path.join(__dirname, 'sample_students.xlsx');
xlsx.writeFile(wb, filePath);

console.log(`Excel file created at: ${filePath}`);
