const fs = require('fs');

const filePath = 'd:\\FYP\\FYP PORTAL CODE\\BE-BackUpBeforeWholeIntegration\\BE-BackUpBeforeWholeIntegration\\server\\controllers\\CoordinatorController\\EvaluateExamCont.js';

const lines = [];
lines.push('const Evaluation = require("../../models/CoordinatorModels/EvaluateExamModel");');
lines.push('const CreateExam = require("../../models/CoordinatorModels/ExamCreationModel");');
lines.push('const Term = require("../../models/AdminModels/fypTerm");');
lines.push('const mongoose = require("mongoose");');
lines.push('const FypRegistration = require("../../models/AdminModels/FypRegistration");');
lines.push('const CLOForExam = require("../../models/CoordinatorModels/CLOForExams");');
lines.push('const Question = require("../../models/CoordinatorModels/ExamQuestionModel");');
lines.push('const PanelDetails = require("../../models/CoordinatorModels/PanelDetails");');
lines.push('const ExamType = require("../../models/CoordinatorModels/ExamTypeModel");');
lines.push('');
lines.push('// Helper Functions');
lines.push('const getQuestionDetails = async (questionId) => {');
lines.push('  try {');
lines.push('    const question = await Question.findById(questionId);');
lines.push('    if (!question) {');
lines.push('      throw new Error("Question not found");');
lines.push('    }');
lines.push('    return question;');
lines.push('  } catch (error) {');
lines.push('    console.error("Error fetching question:", error);');
lines.push('    throw error;');
lines.push('  }');
lines.push('};');
lines.push('');
lines.push('const getExamTypeName = async (examTypeId) => {');
lines.push('  const examType = await ExamType.findById(examTypeId);');
lines.push('  return examType ? examType.examName : "";');
lines.push('};');
lines.push('');
lines.push('const calculateAverageCLOPercentage = (student) => {');
lines.push('  const cloIds = new Set();');
lines.push('  student.evaluationsByExaminers?.forEach((examiner) => {');
lines.push('    examiner.evaluations?.forEach((cloForExam) => {');
lines.push('      cloForExam.cloEvaluations?.forEach((cloEvaluation) => {');
lines.push('        if (cloEvaluation.cloId) {');
lines.push('          cloIds.add(cloEvaluation.cloId.toString());');
lines.push('        }');
lines.push('      });');
lines.push('    });');
lines.push('  });');
lines.push('');
lines.push('  const cloData = {};');
lines.push('  cloIds.forEach((cloId) => {');
lines.push('    cloData[cloId] = { sum: 0, count: 0 };');
lines.push('  });');
lines.push('');
lines.push('  student.evaluationsByExaminers?.forEach((examiner) => {');
lines.push('    examiner.evaluations?.forEach((evaluation) => {');
lines.push('      evaluation.cloEvaluations?.forEach((cloEvaluation) => {');
lines.push('        if (!cloEvaluation.cloId) return;');
lines.push('        const cloId = cloEvaluation.cloId.toString();');
lines.push('        if (cloData[cloId]) {');
lines.push('          cloData[cloId].sum += evaluation.obtainedCLOPercentage || 0;');
lines.push('          cloData[cloId].count += 1;');
lines.push('          cloData[cloId].totalCLOPercentage = evaluation.totalCLOPercentage || 0;');
lines.push('        }');
lines.push('      });');
lines.push('    });');
lines.push('  });');
lines.push('');
lines.push('  const obtainedAverageofCLO = [];');
lines.push('  for (const cloId in cloData) {');
lines.push('    const { sum, count, totalCLOPercentage } = cloData[cloId];');
lines.push('    obtainedAverageofCLO.push({');
lines.push('      cloId,');
lines.push('      averageCLOPercentage: count > 0 ? sum / count : 0,');
lines.push('      totalCLOPercentage,');
lines.push('    });');
lines.push('  }');
lines.push('');
lines.push('  return obtainedAverageofCLO;');
lines.push('};');
lines.push('');
lines.push('const calculateEvaluations = async (evaluations, examWeightage) => {');
lines.push('  const evalsWithQuestions = await Promise.all(');
lines.push('    evaluations.map(async (evalItem) => {');
lines.push('      const totalCLOPercentage = examWeightage / (evaluations.length || 1);');
lines.push('      let totalObtainedMarks = 0;');
lines.push('      let totalMarks = 0;');
lines.push('');
lines.push('      const cloEvaluations = evalItem.cloEvaluations ? await Promise.all(');
lines.push('        evalItem.cloEvaluations.map(async (cloEval) => {');
lines.push('          let totalQuestionMarks = 0;');
lines.push('          let totalObtainedMarksQuestions = 0;');
lines.push('          let questionWeightage = 0;');
lines.push('');
lines.push('          const questions = cloEval.questions ? await Promise.all(');
lines.push('            cloEval.questions.map(async (question) => {');
lines.push('              const quest = await getQuestionDetails(question.questionId);');
lines.push('              questionWeightage = quest.marks;');
lines.push('              const obtainedMarks = question.marks;');
lines.push('              totalQuestionMarks += questionWeightage;');
lines.push('              totalObtainedMarksQuestions += obtainedMarks;');
lines.push('');
lines.push('              return {');
lines.push('                questionId: question.questionId,');
lines.push('                marks: obtainedMarks,');
lines.push('                obtainedPercentage: obtainedMarks,');
lines.push('              };');
lines.push('            })');
lines.push('          ) : [];');
lines.push('');
lines.push('          totalObtainedMarks += totalObtainedMarksQuestions;');
lines.push('          totalMarks += totalQuestionMarks;');
lines.push('');
lines.push('          return {');
lines.push('            cloId: cloEval.cloId,');
lines.push('            questions,');
lines.push('            totalPercentage: questionWeightage,');
lines.push('            obtainedPercentage: 0,');
lines.push('          };');
lines.push('        })');
lines.push('      ) : [];');
lines.push('');
lines.push('      return {');
lines.push('        cloForExamId: evalItem.cloForExamId,');
lines.push('        cloEvaluations,');
lines.push('        totalCLOPercentage,');
lines.push('        obtainedCLOPercentage: totalMarks > 0 ? (totalObtainedMarks / totalMarks) * totalCLOPercentage : 0,');
lines.push('      };');
lines.push('    })');
lines.push('  );');
lines.push('');
lines.push('  return evalsWithQuestions;');
lines.push('};');
lines.push('');
lines.push('// Evaluation Handlers');
lines.push('const addEvaluationMarks = async (req, res) => {');
lines.push('  try {');
lines.push('    const { groupId, termId, examId, examinerId, evaluations, feedback, panelId } = req.body;');
lines.push('    if (!mongoose.Types.ObjectId.isValid(termId)) return res.status(400).json({ error: "Invalid termId" });');
lines.push('');
lines.push('    const exam = await CreateExam.findById(examId).populate("ExamType CLOForExams");');
lines.push('    if (!exam) return res.status(404).json({ error: "Exam not found" });');
lines.push('');
lines.push('    const examName = exam.ExamType.examName;');
lines.push('    const examTypeFor = exam.ExamType.examTypeFor;');
lines.push('');
lines.push('    let containsCLO = false;');
lines.push('    if (exam.CLOForExams) {');
lines.push('      const cloDoc = await CLOForExam.findById(exam.CLOForExams).populate("CLOs");');
lines.push('      containsCLO = cloDoc && cloDoc.CLOs.length > 0;');
lines.push('    }');
lines.push('');
lines.push('    const groupReg = await FypRegistration.findById(groupId);');
lines.push('    if (!groupReg) return res.status(404).json({ error: "Group not found" });');
lines.push('    const supervisorId = groupReg.selectedOption;');
lines.push('');
lines.push('    const existing = await Evaluation.findOne({ supervisorId, "terms.termId": termId, "terms.exams.examId": examId });');
lines.push('    if (existing) {');
lines.push('       const t = existing.terms.find(t => t.termId.toString() === termId.toString());');
lines.push('       const ex = t?.exams.find(e => e.examId.toString() === examId.toString());');
lines.push('       const g = ex?.fypGroups.find(g => g.groupId.toString() === groupId.toString());');
lines.push('       if (g?.students.some(s => s.evaluationsByExaminers.some(ev => ev.examinerId.toString() === examinerId.toString()))) {');
lines.push('         return res.status(400).json({ error: "Already marked" });');
lines.push('       }');
lines.push('    }');
lines.push('');
lines.push('    let result;');
lines.push('    if (containsCLO) {');
lines.push('      result = await handleEvaluationWithCLOs(groupId, termId, examId, examName, examTypeFor, examinerId, evaluations, exam.ExamWeightage, feedback, panelId, supervisorId);');
lines.push('    } else {');
lines.push('      const type = await getExamTypeName(exam.ExamType);');
lines.push('      result = await handleEvaluationWithoutCLOs(groupId, termId, examId, examName, examTypeFor, examinerId, evaluations, type, exam.ExamWeightage, supervisorId);');
lines.push('    }');
lines.push('    res.status(200).json({ message: "Success", evaluation: result });');
lines.push('  } catch (err) { res.status(500).json({ error: err.message }); }');
lines.push('};');
lines.push('');
lines.push('const handleEvaluationWithCLOs = async (groupId, termId, examId, examName, examTypeFor, examinerId, evaluations, weight, feedback, panelId, supervisorId) => {');
lines.push('  let term = await Evaluation.findOne({ supervisorId });');
lines.push('  if (!term) {');
lines.push('    term = new Evaluation({ supervisorId, terms: [{ termId, exams: [{ examId, examName, examTypeFor, fypGroups: [{ groupId, panelId, students: await Promise.all(evaluations.map(async s => ({');
lines.push('      studentId: s.studentId,');
lines.push('      evaluationsByExaminers: [{ examinerId, evaluations: s.evaluations ? await calculateEvaluations(s.evaluations, weight) : [], marks: s.marks || 0, feedback: feedback || "" }],');
lines.push('      obtainedAverage: 0, obtainedAverageofCLO: []');
lines.push('    })))}]}]}]});');
lines.push('  } else {');
lines.push('    let specificTerm = term.terms.find(t => t.termId.toString() === termId.toString());');
lines.push('    if (!specificTerm) {');
lines.push('      specificTerm = { termId, exams: [{ examId, examName, examTypeFor, fypGroups: [{ groupId, panelId, students: await Promise.all(evaluations.map(async s => ({');
lines.push('        studentId: s.studentId,');
lines.push('        evaluationsByExaminers: [{ examinerId, evaluations: s.evaluations ? await calculateEvaluations(s.evaluations, weight) : [], marks: s.marks || 0, feedback: feedback || "" }],');
lines.push('        obtainedAverage: 0, obtainedAverageofCLO: []');
lines.push('      })))}]}]};');
lines.push('      term.terms.push(specificTerm);');
lines.push('    } else {');
lines.push('      let exam = specificTerm.exams.find(e => e.examId.toString() === examId.toString());');
lines.push('      if (!exam) {');
lines.push('        specificTerm.exams.push({ examId, examName, examTypeFor, fypGroups: [{ groupId, panelId, students: await Promise.all(evaluations.map(async s => ({');
lines.push('          studentId: s.studentId,');
lines.push('          evaluationsByExaminers: [{ examinerId, evaluations: s.evaluations ? await calculateEvaluations(s.evaluations, weight) : [], marks: s.marks || 0, feedback: feedback || "" }],');
lines.push('          obtainedAverage: 0, obtainedAverageofCLO: []');
lines.push('        })))}]});');
lines.push('      } else {');
lines.push('        let group = exam.fypGroups.find(g => g.groupId.toString() === groupId.toString());');
lines.push('        if (!group) {');
lines.push('          exam.fypGroups.push({ groupId, panelId, students: await Promise.all(evaluations.map(async s => ({');
lines.push('            studentId: s.studentId,');
lines.push('            evaluationsByExaminers: [{ examinerId, evaluations: s.evaluations ? await calculateEvaluations(s.evaluations, weight) : [], marks: s.marks || 0, feedback: feedback || "" }],');
lines.push('            obtainedAverage: 0, obtainedAverageofCLO: []');
lines.push('          })))});');
lines.push('        } else {');
lines.push('           await Promise.all(evaluations.map(async s => {');
lines.push('             let st = group.students.find(sd => sd.studentId.toString() === s.studentId.toString());');
lines.push('             if (!st) {');
lines.push('               group.students.push({ studentId: s.studentId, evaluationsByExaminers: [{ examinerId, evaluations: s.evaluations ? await calculateEvaluations(s.evaluations, weight) : [], marks: s.marks || 0, feedback: feedback || "" }], obtainedAverage: 0, obtainedAverageofCLO: [] });');
lines.push('             } else {');
lines.push('               if (!st.evaluationsByExaminers.some(ev => ev.examinerId.toString() === examinerId.toString())) {');
lines.push('                 st.evaluationsByExaminers.push({ examinerId, evaluations: s.evaluations ? await calculateEvaluations(s.evaluations, weight) : [], marks: s.marks || 0, feedback: feedback || "" });');
lines.push('               }');
lines.push('             }');
lines.push('           }));');
lines.push('        }');
lines.push('      }');
lines.push('    }');
lines.push('  }');
lines.push('');
lines.push('  term.terms?.forEach(t => t.exams?.forEach(e => {');
lines.push('    if (["Attendance-I", "Attendance-II", "Orientation"].includes(e.examName)) return;');
lines.push('    e.fypGroups?.forEach(g => g.students?.forEach(s => {');
lines.push('      const tot = s.evaluationsByExaminers?.reduce((sm, ex) => sm + (ex.evaluations?.reduce((cs, c) => cs + (c.obtainedCLOPercentage || 0), 0) || 0), 0) || 0;');
lines.push('      s.obtainedAverage = tot / (s.evaluationsByExaminers?.length || 1);');
lines.push('      s.obtainedAverageofCLO = calculateAverageCLOPercentage(s);');
lines.push('    }));');
lines.push('  }));');
lines.push('');
lines.push('  await PanelDetails.updateOne({ "PanelMembers.member": examinerId }, { $set: { "PanelMembers.$.evaluationStatus": "marked" } });');
lines.push('  await term.save();');
lines.push('  return term;');
lines.push('};');
lines.push('');
lines.push('const handleEvaluationWithoutCLOs = async (groupId, termId, examId, examName, examTypeFor, examinerId, evaluations, type, weight, supervisorId) => {');
lines.push('  if (["Attendance-I", "Attendance-II", "Final Defense"].includes(type)) return storeMarksForAttendance(groupId, termId, examId, examName, examTypeFor, evaluations, examinerId, weight, supervisorId);');
lines.push('  if (type === "Orientation") return storeMarksForOrientation(groupId, termId, examId, examName, examTypeFor, evaluations, examinerId, weight, supervisorId);');
lines.push('  throw new Error("Invalid type: " + type);');
lines.push('};');
lines.push('');
lines.push('const storeMarksForAttendance = async (groupId, termId, examId, examName, examTypeFor, evals, exId, weight, supId) => {');
lines.push('  let term = await Evaluation.findOne({ supervisorId: supId });');
lines.push('  const marks = evals.map(e => ({ studentId: e.studentId, marks: e.marks }));');
lines.push('');
lines.push('  if (!term) {');
lines.push('    term = new Evaluation({ supervisorId: supId, terms: [{ termId, exams: [{ examId, examName, examTypeFor, fypGroups: [{ groupId, students: marks.map(m => ({ studentId: m.studentId, evaluationsByExaminers: [{ examinerId: exId, marks: m.marks, totalWeightage: weight }] })) }] }] }] });');
lines.push('  } else {');
lines.push('    let st = term.terms.find(t => t.termId.toString() === termId.toString());');
lines.push('    if (!st) {');
lines.push('      st = { termId, exams: [{ examId, examName, examTypeFor, fypGroups: [{ groupId, students: marks.map(m => ({ studentId: m.studentId, evaluationsByExaminers: [{ examinerId: exId, marks: m.marks, totalWeightage: weight }] })) }] }] };');
lines.push('      term.terms.push(st);');
lines.push('    } else {');
lines.push('      let ex = st.exams.find(e => e.examId.toString() === examId.toString());');
lines.push('      if (!ex) {');
lines.push('        ex = { examId, examName, examTypeFor, fypGroups: [{ groupId, students: marks.map(m => ({ studentId: m.studentId, evaluationsByExaminers: [{ examinerId: exId, marks: m.marks, totalWeightage: weight }] })) }] };');
lines.push('        st.exams.push(ex);');
lines.push('      } else {');
lines.push('        let g = ex.fypGroups.find(gr => gr.groupId.toString() === groupId.toString());');
lines.push('        if (!g) {');
lines.push('          g = { groupId, students: marks.map(m => ({ studentId: m.studentId, evaluationsByExaminers: [{ examinerId: exId, marks: m.marks, totalWeightage: weight }] })) };');
lines.push('          ex.fypGroups.push(g);');
lines.push('        } else {');
lines.push('          marks.forEach(m => {');
lines.push('            let s = g.students.find(sd => sd.studentId.toString() === m.studentId.toString());');
lines.push('            if (!s) g.students.push({ studentId: m.studentId, evaluationsByExaminers: [{ examinerId: exId, marks: m.marks, totalWeightage: weight }] });');
lines.push('            else {');
lines.push('              let ev = s.evaluationsByExaminers.find(e => e.examinerId.toString() === exId.toString());');
lines.push('              if (!ev) s.evaluationsByExaminers.push({ examinerId: exId, marks: m.marks, totalWeightage: weight });');
lines.push('              else ev.marks = m.marks;');
lines.push('            }');
lines.push('          });');
lines.push('        }');
lines.push('      }');
lines.push('    }');
lines.push('  }');
lines.push('  const foundT = term.terms.find(t => t.termId.toString() === termId.toString());');
lines.push('  const curEx = foundT?.exams.find(e => e.examId.toString() === examId.toString());');
lines.push('  curEx?.fypGroups?.forEach(g => g.students?.forEach(s => {');
lines.push('    const tot = s.evaluationsByExaminers?.reduce((sm, e) => sm + (e.marks || 0), 0) || 0;');
lines.push('    s.obtainedAverage = tot / (s.evaluationsByExaminers?.length || 1);');
lines.push('  }));');
lines.push('  await term.save(); return term;');
lines.push('};');
lines.push('');
lines.push('const storeMarksForOrientation = async (groupId, termId, examId, examName, examTypeFor, evals, exId, weight, supId) => {');
lines.push('  let term = await Evaluation.findOne({ supervisorId: supId });');
lines.push('  const marks = evals.map(e => ({ studentId: e.studentId, marks: e.marks }));');
lines.push('  if (!term) {');
lines.push('    term = new Evaluation({ supervisorId: supId, terms: [{ termId, exams: [{ examId, examName, examTypeFor, fypGroups: [{ groupId, students: marks.map(m => ({ studentId: m.studentId, evaluationsByExaminers: [{ examinerId: exId, marks: m.marks, totalWeightage: weight }] })) }] }] }] });');
lines.push('  } else {');
lines.push('    let st = term.terms.find(t => t.termId.toString() === termId.toString());');
lines.push('    if (!st) {');
lines.push('      st = { termId, exams: [{ examId, examName, examTypeFor, fypGroups: [{ groupId, students: marks.map(m => ({ studentId: m.studentId, evaluationsByExaminers: [{ examinerId: exId, marks: m.marks, totalWeightage: weight }] })) }] }] };');
lines.push('      term.terms.push(st);');
lines.push('    } else {');
lines.push('      let ex = st.exams.find(e => e.examId.toString() === examId.toString());');
lines.push('      if (!ex) st.exams.push({ examId, examName, examTypeFor, fypGroups: [{ groupId, students: marks.map(m => ({ studentId: m.studentId, evaluationsByExaminers: [{ examinerId: exId, marks: m.marks, totalWeightage: weight }] })) }] });');
lines.push('      else {');
lines.push('        let g = ex.fypGroups.find(gr => gr.groupId.toString() === groupId.toString());');
lines.push('        if (!g) ex.fypGroups.push({ groupId, students: marks.map(m => ({ studentId: m.studentId, evaluationsByExaminers: [{ examinerId: exId, marks: m.marks, totalWeightage: weight }] })) });');
lines.push('        else {');
lines.push('          marks.forEach(m => {');
lines.push('            let s = g.students.find(sd => sd.studentId.toString() === m.studentId.toString());');
lines.push('            if (!s) g.students.push({ studentId: m.studentId, evaluationsByExaminers: [{ examinerId: exId, marks: m.marks, totalWeightage: weight }] });');
lines.push('            else {');
lines.push('              let ev = s.evaluationsByExaminers.find(e => e.examinerId.toString() === exId.toString());');
lines.push('              if (!ev) s.evaluationsByExaminers.push({ examinerId: exId, marks: m.marks, totalWeightage: weight });');
lines.push('              else ev.marks = m.marks;');
lines.push('            }');
lines.push('          });');
lines.push('        }');
lines.push('      }');
lines.push('    }');
lines.push('  }');
lines.push('  await term.save(); return term;');
lines.push('};');
lines.push('');
lines.push('const fetchAllExamOfGroup = async (req, res) => {');
lines.push('  try {');
lines.push('    let { termId, groupId } = req.params;');
lines.push('    const evaluations = await Evaluation.find({ "terms.termId": termId });');
lines.push('    let groupExams = [];');
lines.push('    evaluations.forEach(ev => {');
lines.push('      const t = ev.terms.find(te => te.termId.toString() === termId);');
lines.push('      t?.exams.forEach(ex => {');
lines.push('        const g = ex.fypGroups.find(gr => gr.groupId.toString() === groupId);');
lines.push('        if (g) groupExams.push({ examId: ex.examId, students: g.students });');
lines.push('      });');
lines.push('    });');
lines.push('    res.status(200).json({ groupExams });');
lines.push('  } catch (err) { res.status(500).json({ error: err.message }); }');
lines.push('};');
lines.push('');
lines.push('const getEvaluationMarks = async (req, res) => {');
lines.push('  try {');
lines.push('    const { supervisorId, termId } = req.params;');
lines.push('    const ev = await Evaluation.findOne({ supervisorId }).populate("terms.termId terms.exams.examId terms.exams.fypGroups.groupId terms.exams.fypGroups.students.studentId");');
lines.push('    if (!ev) return res.status(404).json({ error: "Not found" });');
lines.push('    const t = ev.terms.find(te => te.termId && te.termId._id.toString() === termId);');
lines.push('    res.status(200).json({ evaluation: t });');
lines.push('  } catch (err) { res.status(500).json({ error: err.message }); }');
lines.push('};');
lines.push('');
lines.push('module.exports = { getEvaluationMarks, addEvaluationMarks, fetchAllExamOfGroup };');

fs.writeFileSync(filePath, lines.join('\\n'), \'utf8\');
console.log(\'File reconstructed successfully.\');
